name: Stock Yield Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  #  画像を保存するために必須

jobs:
  check-stocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance line-bot-sdk matplotlib

      - name: Run stock yield monitor
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          GITHUB_USERNAME: "poohredtem"
          GITHUB_REPOSITORY: "stock-yield-checker"
        run: python main.py

      - name: Save plots to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add plots/
          git commit -m "Update stock plots" || echo "No changes"
          git push

      - name: Save plots to repository
        run: sleep 60
